name: controldespacho
description: Control de Despacho, desarrollado por la empresa 'Control Plus'.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  animated_splash_screen: ^1.3.0
  get: ^4.6.5
  mysql1: ^0.20.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.0
  http: ^0.13.4
  intl: ^0.17.0
  majascan: ^0.5.0
  geolocator: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.3


  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo-control-plus.png"


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/buttons/
